/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-02-06 15:27:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import jp.ac.asojuku.bookstore.param.SessionConst;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"systemerror.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("<title>ログイン</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://localhost:8080/bookstore/view/css/bookstore.css\">\r\n");
      out.write("<script src=\"http://localhost:8080/bootstore/view/js/bookstore.js\"></script>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("  <script type='text/javascript' src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("  <script type='text/javascript' src=\"//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tdiv #error {\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("}\r\n");
      out.write("#in{\r\n");
      out.write("\tbackground-color:snow;\r\n");
      out.write("}\r\n");
      out.write("#in h1{\r\n");
      out.write("\tcolor:hotpink;\r\n");
      out.write("\t float:left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbarEexample7\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">ASO書店</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarEexample7\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/top\">トップ画面</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">買い物かご</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("    <!-- <form >\r\n");
      out.write("         <input type=\"text\" name=\"username\" >\r\n");
      out.write("         <input type=\"password\" name=\"password\">\r\n");
      out.write("         <button type=\"submit\">Sign in</button>\r\n");
      out.write("     </form>!-->\r\n");
      out.write("     <!-- /form -->\r\n");
      out.write("     <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t  <div class=\"row\" id=\"pwd-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t    <div class=\"col-md-4\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t    <div class=\"col-md-4\">\r\n");


String LoginRequestMsg =  (String)request.getAttribute("LoginRequestMsg");
String CSRFT = (String)session.getAttribute(SessionConst.SESSION_LOGUIN_TOKEN1);
System.out.println("@"+CSRFT +"kkkkkkkkkkkkkkk");
//request.setAttribute("Csrft",CSRFT);
//System.out.println("???????" +request.getAttribute("Csrft"));
if( LoginRequestMsg != null ){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"error\">\r\n");
      out.print( LoginRequestMsg );
      out.write("\r\n");
      out.write("</div>\r\n");

}

      out.write("\r\n");
      out.write("\t\t      <section class=\"login-form\"  >\r\n");
      out.write("\t\t        <form  action=\"");
      out.print(request.getContextPath() );
      out.write("/auth\" method=\"POST\" role=\"login\" id=\"in\">\r\n");
      out.write("\t\t        \r\n");
      out.write("\r\n");
      out.write("\t\t          <h1>LOGIN</h1>\r\n");
      out.write("\t\t          <!--<img src=\"http://i.imgur.com/RcmcLv4.png\" class=\"img-responsive\" alt=\"\" />!-->\r\n");
      out.write("\t\t          <input type=\"email\" name=\"memb_id\" placeholder=\"Email\" required class=\"form-control input-lg\"  />\r\n");
      out.write("\r\n");
      out.write("\t\t          <input type=\"password\" name=\"password\" class=\"form-control input-lg\" id=\"password\" placeholder=\"Password\"  />\r\n");
      out.write("\t\t          <input type=\"hidden\" name=\"_CSRFToken\" value=");
      out.print(URLEncoder.encode(CSRFT,"UTF-8"));
      out.write(" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t          <div class=\"pwstrength_viewport_progress\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t          <button type=\"submit\" name=\"go\" class=\"btn btn-lg btn-primary btn-block\">Sign in</button>\r\n");
      out.write("\t\t          <div>\r\n");
      out.write("\t\t            <a href=\"");
      out.print(request.getContextPath() );
      out.write("/MemberNew\" onclick=\"document.form.submit(); return false;\">新規会員登録</a> or <a href=\"#\">パスワードをお忘れ</a>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\r\n");
      out.write("\t\t        </form>\r\n");
      out.write("\r\n");
      out.write("\t\t        <div class=\"form-links\">\r\n");
      out.write("\t\t          \r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t      </section>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\r\n");
      out.write("\t\t     <div class=\"col-md-4\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
