/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-02-09 07:53:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jp.ac.asojuku.bookstore.param.RequestConst;
import jp.ac.asojuku.bookstore.param.SessionConst;
import jp.ac.asojuku.bookstore.dto.MemberDTO;
import jp.ac.asojuku.bookstore.error.ErrorsAction;
import jp.ac.asojuku.bookstore.error.ErrorAction;
import java.net.URLEncoder;

public final class NewMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ja\">\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("    <title>新規会員登録</title>\r\n");
      out.write("\t<link href=\"view/css/bookstore.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"view/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    #error {\r\n");
      out.write("    color red;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    nav{\r\n");
      out.write("      background: red;\r\n");
      out.write("    }\r\n");
      out.write("    .in{\r\n");
      out.write("    color:#ffcc99;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
 
ErrorsAction  errors = (ErrorsAction)request.getAttribute(RequestConst.REQUEST_ERRORS);
String MemberToken1 = (String)session.getAttribute(SessionConst.SESSION_MEMBER_TOKEN1);

      out.write('\r');
      out.write('\n');
MemberDTO memberINFO = (MemberDTO)request.getAttribute(RequestConst.REQUEST_MEMBER_INFO); 
      out.write("\r\n");
      out.write("\t<!-- 1.ナビゲーションバーの設定 -->\r\n");
      out.write("\t<div class=\"dropdown\">\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbarEexample7\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"#\">ASO書店</a>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarEexample7\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/top\">トップ画面</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">買い物かご</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/login\">ログイン</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--  <div class=\"well\">-->\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("    \t<fieldset>\r\n");
      out.write("    \t<ul class=\"list-group\">\r\n");
      out.write("\t  \t\t<li class=\"list-group-item list-group-item-danger\">\r\n");
      out.write("\t\t\t<p class=\"\">会員登録画面です。お手数ですが、全ての入力項目に必要項目に入力してください。最後に送信ボタンをおしてください。</p></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t\r\n");
 if( errors != null ){ 
      out.write("\r\n");
      out.write("\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t<li class=\"list-group-item list-group-item-danger\">\r\n");
      out.write("\t");
 for(ErrorAction err : errors.getList()){
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<p>");
      out.print( err.getMessage() );
      out.write("</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t</li>\r\n");
      out.write("\t</ul>\r\n");
} 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   <form class=\"form-horizontal\" action=\"");
      out.print(request.getContextPath() );
      out.write("/entrymember\" method=\"POST\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"name\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">お名前</label>\r\n");
      out.write("\r\n");
      out.write("         \t  <div class=\"col col-xs-5 col-sm-3 col-md-3\">\r\n");
      out.write("\r\n");
      out.write("              <input type=\"text\" name=\"name1\" id=\"name1\" class=\"form-control\" placeholder=\"姓\"\r\n");
      out.write("              ");
 if(memberINFO !=null) { 
      out.write(" \r\n");
      out.write("              \tvalue=");
      out.print(memberINFO.getName_sei());
      out.write("\r\n");
      out.write("             ");
 } 
      out.write(" >\r\n");
      out.write("\t\t\t\t<p class=\"help-block in\">お名前を入力してください。（漢字または英字）</p>\r\n");
      out.write("          \t</div>\r\n");
      out.write("\r\n");
      out.write("          \t<div class=\"col col-xs-5 col-sm-3 col-md-3\">\r\n");
      out.write("\r\n");
      out.write("              <input type=\"text\" name=\"name2\" id=\"name2\" class=\"form-control\" placeholder=\"名\"\r\n");
      out.write("              ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getName_mei() );
} 
      out.write(" >\r\n");
      out.write("\t\t\t\r\n");
      out.write("          \t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("          \t<div class=\"col-xs-offset-2 col-sm-offset-2 col-md-offset-3\"></div>\r\n");
      out.write("\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("         \t  <label for=\"name\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">ふりがな</label>\r\n");
      out.write("\r\n");
      out.write("          \t<div class=\"col col-xs-5 col-sm-3 col-md-3\">\r\n");
      out.write("\r\n");
      out.write("              <input type=\"text\" name=\"name3\" id=\"name3\" class=\"form-control\" placeholder=\"せい\"\r\n");
      out.write("              ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getName_hurigana_sei() );
} 
      out.write(" >\r\n");
      out.write("\t\t\t <p class=\"help-block in\">ふりがなを入力してください。（ひらがな）</p>\r\n");
      out.write("          \t</div>\r\n");
      out.write("\r\n");
      out.write("          \t<div class=\"col col-xs-5 col-sm-3 col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            \t<input type=\"text\" name=\"name4\" id=\"name4\" class=\"form-control\" placeholder=\"めい\"\r\n");
      out.write("            \t");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getName_hurigana_mei() );
} 
      out.write(" >\r\n");
      out.write("\r\n");
      out.write("          \t</div>\r\n");
      out.write("\r\n");
      out.write("          \t<div class=\"col-xs-offset-2 col-sm-offset-2 col-md-offset-3\"></div>\r\n");
      out.write("\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"email\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">ニックネーム</label>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col col-xs-12 col-sm-6 col-md-7\">\r\n");
      out.write("\r\n");
      out.write("              <input type=\"text\" name=\"nickname\"  id=\"nickname\" class=\"form-control\" placeholder=\"ニックネーム\"\r\n");
      out.write("              ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getNickname() );
} 
      out.write(" >\r\n");
      out.write("\r\n");
      out.write("          \t</div>\r\n");
      out.write("\r\n");
      out.write("         \t \t<div class=\"col-xs-offset-0 col-sm-offset-2 col-md-offset-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-xs-offset-2 col-sm-offset-2 col-md-offset-3\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \t <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         \t  <label for=\"zipcode\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">郵便番号</label>\r\n");
      out.write("\r\n");
      out.write("          \t<div class=\"col col-xs-7 col-sm-4 col-md-4\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("                <span class=\"input-group-addon\">〒</span>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\" name=\"yuubinno\" id=\"zipcode\" class=\"form-control\" placeholder=\"000-0000\"\r\n");
      out.write("                ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getYuubinNo() );
} 
      out.write(" >\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("            \t</div>\r\n");
      out.write("\t\t\t\t<p class=\"help-block in\">郵便番号入力してください。（半角）</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-xs-offset-5 col-sm-offset-4 col-md-offset-5\"></div>\r\n");
      out.write("\r\n");
      out.write("        \t</div>\r\n");
      out.write("\r\n");
      out.write("        \t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("          \t\t<label for=\"pref\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">住所</label>\r\n");
      out.write("\r\n");
      out.write("          \t\t<div class=\"col col-xs-7 col-sm-4 col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            \t\t<select name=\"pref\" id=\"pref\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t   \r\n");
      out.write("  \t\t\t           <option value=\"北海道\">北海道</option>\r\n");
      out.write("\r\n");
      out.write("  \t    \t\t       <option value=\"青森県\">青森県</option>\r\n");
      out.write("\r\n");
      out.write("  \t        \t\t   <option value=\"岩手県\">岩手県</option>\r\n");
      out.write("\r\n");
      out.write("  \t            \t <option value=\"宮城県\">宮城県</option>\r\n");
      out.write("\r\n");
      out.write("  \t          \t\t <option value=\"秋田県\">秋田県</option>\r\n");
      out.write("\r\n");
      out.write("  \t           \t\t <option value=\"山形県\">山形県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"福島県\">福島県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"茨城県\">茨城県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"栃木県\">栃木県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"群馬県\">群馬県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"埼玉県\">埼玉県</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"千葉県\">千葉県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"東京都\">東京都</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"神奈川県\">神奈川県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"新潟県\">新潟県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"山梨県\">山梨県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"長野県\">長野県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"富山県\">富山県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"石川県\">石川県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"福井県\">福井県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"岐阜県\">岐阜県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"静岡県\">静岡県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"愛知県\">愛知県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"三重県\">三重県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"滋賀県\">滋賀県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"京都府\">京都府</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"大阪府\">大阪府</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"兵庫県\">兵庫県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"奈良県\">奈良県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"和歌山県\">和歌山県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"鳥取県\">鳥取県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"島根県\">島根県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"岡山県\">岡山県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"広島県\">広島県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"山口県\">山口県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"徳島県\">徳島県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"香川県\">香川県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"愛媛県\">愛媛県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"高知県\">高知県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"福岡県\">福岡県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"佐賀県\">佐賀県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"長崎県\">長崎県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"熊本県\">熊本県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"大分県\">大分県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"宮崎県\">宮崎県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"鹿児島県\">鹿児島県</option>\r\n");
      out.write("\r\n");
      out.write("  \t               <option value=\"沖縄県\">沖縄県</option>\r\n");
      out.write("\r\n");
      out.write("  \t             </select>\r\n");
      out.write("\t\t\t\t<p class=\"help-block in\">都道府県を選択してください。</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-xs-offset-5 col-sm-offset-4 col-md-offset-6\"></div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3\">\r\n");
      out.write("\r\n");
      out.write("                  <input type=\"text\" name=\"addr1\" id=\"addr1\" class=\"form-control\" placeholder=\"市区町村名\"\r\n");
      out.write("                  ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getAddres1() );
} 
      out.write(" >\r\n");
      out.write("\r\n");
      out.write("                  <p class=\"help-block in\">住所は2つに分けてご記入ください。</p>\r\n");
      out.write("\r\n");
      out.write("                  <input type=\"text\" name=\"addr2\" id=\"addr2\" class=\"form-control\" placeholder=\"番地・ビル名\"\r\n");
      out.write("                  ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getAddres2() );
} 
      out.write(" >\r\n");
      out.write("\r\n");
      out.write("                  <p class=\"help-block in\">マンション名は必ず記入してください。</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <label for=\"tel\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">電話番号</label>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-xs-12 colcol-xs-10 col-sm-6 col-md-7\">\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"tel\" name=\"tel1\" id=\"tel1\" class=\"form-control\" placeholder=\"080\"\r\n");
      out.write("                    ");
if(memberINFO!= null){ 
      out.write("value=");
      out.print(memberINFO.getTel1() );
} 
      out.write(" >\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"input-group-addon\">-</span>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"tel\" name=\"tel2\" id=\"tel2\" class=\"form-control\" placeholder=\"0000\"\r\n");
      out.write("                    ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getTel2() );
} 
      out.write(" >\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"input-group-addon\">-</span>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"tel\" name=\"tel3\" id=\"tel3\" class=\"form-control\" placeholder=\"0000\"\r\n");
      out.write("                    ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getTel3() );
} 
      out.write(" >\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p class=\"help-block in\">携帯番号または自宅電話番号</p>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-xs-offset-2 col-sm-offset-2 col-md-offset-2\"></div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <label for=\"email\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">メールアドレス</label>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col col-xs-12 col-sm-6 col-md-7\">\r\n");
      out.write("\r\n");
      out.write("                  <input type=\"email\" name=\"email\" id=\"email\" class=\"form-control\" placeholder=\"メールアドレスを入力してください\"\r\n");
      out.write("                  ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getMail1() );
} 
      out.write(" >\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-xs-offset-0 col-sm-offset-2 col-md-offset-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <label for=\"email2\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">メールアドレス再度確認</label>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col col-xs-12 col-sm-6 col-md-7\">\r\n");
      out.write("\r\n");
      out.write("                  <input type=\"email\" name=\"email2\" id=\"email2\" class=\"form-control\" placeholder=\"メールアドレスを再度入力してください\"\r\n");
      out.write("                  ");
if(memberINFO != null){ 
      out.write("value=");
      out.print(memberINFO.getMail2() );
} 
      out.write(" >\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-xs-offset-0 col-sm-offset-2 col-md-offset-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <label for=\"email\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">パスワード</label>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col col-xs-12 col-sm-6 col-md-7\">\r\n");
      out.write("\r\n");
      out.write("                  <input type=\"password\" name=\"password\" id=\"pass1\" class=\"form-control\" placeholder=\"パスワード\" \">\r\n");
      out.write("\t\t\t\t<p class=\"help-block in\">パスワードは、八文字以上。</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-xs-offset-0 col-sm-offset-2 col-md-offset-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <label for=\"email\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">パスワード再度入力</label>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col col-xs-12 col-sm-6 col-md-7\">\r\n");
      out.write("\r\n");
      out.write("                  <input type=\"password\" name=\"password2\"  id=\"pass2\"class=\"form-control\" placeholder=\"パスワード再入力\" >\r\n");
      out.write("\t\t\t\t  <input type=\"hidden\" name=\"Member_CSRFToken\" value=");
      out.print(URLEncoder.encode(MemberToken1,"UTF-8"));
      out.write(" />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-xs-offset-0 col-sm-offset-2 col-md-offset-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("          \t\t<label for=\"pref\" class=\"col col-xs-12 col-sm-4 col-md-3 control-label in\">性別</label>\r\n");
      out.write("\r\n");
      out.write("          \t\t<div class=\"col col-xs-7 col-sm-4 col-md-3\">\r\n");
      out.write("\r\n");
      out.write("  \t          \t\t<select name=\"sex\" id=\"pref\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t    \t<option value=\"men\">男性</option>\r\n");
      out.write("  \t\t\t\t        <option value=\"woman\">女性</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \t\t            </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-xs-offset-5 col-sm-offset-4 col-md-offset-6\"></div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col col-xs-9 col-xs-offset-3 col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3\">\r\n");
      out.write("\t\t\t\t  <button type=\"submit\" class=\"btn btn-default\">送信</button>\r\n");
      out.write("                  <!--<button type=\"submit\" class=\"btn btn-success btn-lg\">登録</button>-->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  <!--  </div>-->\r\n");
      out.write("\r\n");
      out.write("  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("  <script src=\"view/js/bootstrap.min.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
