/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-02-06 16:15:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jp.ac.asojuku.bookstore.param.RequestConst;
import jp.ac.asojuku.bookstore.param.SessionConst;
import jp.ac.asojuku.bookstore.dto.MemberDTO;
import jp.ac.asojuku.bookstore.error.ErrorsAction;
import jp.ac.asojuku.bookstore.error.ErrorAction;
import jp.ac.asojuku.bookstore.dto.SystemError;
import java.io.*;
import java.util.*;
import java.text.*;

public final class systemerror_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ja\">\n");
      out.write("\n");
      out.write("  <head>\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("    <title>新規会員登録</title>\n");
      out.write("\t<!-- bookstore css -->\n");
      out.write("\t<link href=\"view/css/bookstore.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <link href=\"view/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("    \n");
      out.write("    \n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write(" \n");
      out.write("    \n");
      out.write(" ");
SystemError system = (SystemError)session.getAttribute("Syserr");
 SystemError systemerr = (SystemError)session.getAttribute("Systemerr");
 
      out.write("\n");
      out.write("\n");
      out.write("  <nav class=\"navbar navbar-inverse\">\n");
      out.write("\t\n");
      out.write("\t\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbarEexample7\">\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"#\">ASO書店</a>\n");
      out.write("\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarEexample7\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/top\">トップ画面</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">買い物かご</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t");
if(system != null){
      out.write("\n");
      out.write("\t\t<ul class=\"list-group\">\n");
      out.write("\t  \t\t<li class=\"list-group-item list-group-item-danger\">\n");
      out.write("\t  \t\t\n");
      out.write("\t\t\t\t\t\t");
      out.print( system.getMailError());
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t  \t\t</li>\n");
      out.write("\t  \t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t");
 }
      out.write('\n');
      out.write('	');
      out.write('	');
if(systemerr != null){
      out.write("\n");
      out.write("\t\t<ul class=\"list-group\">\n");
      out.write("\t  \t\t<li class=\"list-group-item list-group-item-danger\">\n");
      out.write("\t  \t\t\n");
      out.write("\t\t\t\t\t\t");
      out.print(systemerr.getSystemError() );
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t  \t\t</li>\n");
      out.write("\t  \t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t");
 }
      out.write("\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\n");
      out.write("  <!-- Include all compiled plugins (below), or include individual files as needed -->\n");
      out.write("  <script src=\"view/js/bootstrap.min.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
