/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-02-06 15:27:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jp.ac.asojuku.bookstore.param.SessionConst;
import jp.ac.asojuku.bookstore.dto.LoginInfoDTO;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("    \n");
      out.write("\t<!-- bookstore css -->\n");
      out.write("\t<link href=\"view/css/bookstore.css\" rel=\"stylesheet\">\n");
      out.write("\t\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <link href=\"view/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\t<title>トップ画面サンプル</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("\n");
      out.write(".container{\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write(".header{\n");
      out.write("\tborder-top:3px solid #000;\n");
      out.write("}\n");
      out.write(".logo{\n");
      out.write("\tmargin:0.5em auto;\n");
      out.write("\tdisplay:block;\n");
      out.write("}\n");
      out.write(".headerNavBtn{\n");
      out.write("\ttext-align:center;\n");
      out.write("\theight:3em;\n");
      out.write("\tline-height:3em;\n");
      out.write("\tcolor:#5F5F5F;\n");
      out.write("\tfont-size:16px;\n");
      out.write("}\n");
      out.write(".headerNavBtn:hover{\n");
      out.write("\tbackground:#EEE;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".section{\n");
      out.write("\tbackground: #232829;\n");
      out.write("\tbackground: -moz-linear-gradient(50% 0% -90deg, #000 0%, #232829 100%);\n");
      out.write("\tbackground: -o-linear-gradient(-90deg, #000 0%, #232829 100%);\n");
      out.write("\tbackground: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0, #000), color-stop(1, #232829));\n");
      out.write("\tbackground: -webkit-linear-gradient(-90deg, #000 0%, #232829 100%);\n");
      out.write("\tbackground: linear-gradient(180deg, #000 0%, #232829 100%);\n");
      out.write("\tpadding: 2em 0 3em;\n");
      out.write("\t-ms-filter: \"progid:DXImageTransform.Microsoft.gradient(startColorstr=#ff000000,endColorstr=#ff232829,GradientType=0)\";\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#ff000000,endColorstr=#ff232829,GradientType=0);\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".mainVisual_wrapper{\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mainVisual_wrapper .container{\n");
      out.write("\tpadding:0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mainVisual_wrapper.section{\n");
      out.write("\tpadding:0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".col_box{\n");
      out.write("\tbackground:#FFF;\n");
      out.write("\tborder-radius:3px;\n");
      out.write("\tpadding:15px 0 15px;\n");
      out.write("\tmargin-bottom:1em;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".copyright{\n");
      out.write("\ttext-align:center;\n");
      out.write("\tmargin:0.5em auto;\n");
      out.write("\tdisplay:block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".taka {\n");
      out.write("    background-color:snow;\n");
      out.write("    padding:10px; /* メニュー全体170px; */\n");
      out.write("    width:270px; /* リンク部分150px; */\n");
      out.write("    /*background-image: url(\"view/img/sa.jpg\")*/\n");
      out.write("}\n");
      out.write(".taka li {\n");
      out.write("    list-style-type:none;  /* リスト記号なし */\n");
      out.write("    /* margin-bottom:5px; */\n");
      out.write("}\n");
      out.write(".taka a {\n");
      out.write("    border:solid 2px;\n");
      out.write("    border-color:white darkblue darkblue white;\n");
      out.write("    padding:5px;\n");
      out.write("    display:block;\n");
      out.write("    font-weight:bold;\n");
      out.write("    font-size:12px;\n");
      out.write("    color:#ffffff;\n");
      out.write("    text-decoration:none;\n");
      out.write("    background-color:#BAD3FF;\n");
      out.write("}\n");
      out.write(".taka a:hover {\n");
      out.write("    border-color:darkblue lightblue lightblue darkblue;\n");
      out.write("    padding:7px 3px 3px 7px;\n");
      out.write("    background-color:#ffcccc;\n");
      out.write("}\n");
      out.write(".taka h1{\n");
      out.write("   font-size: 17px;\n");
      out.write("   color:#ffcc99;\n");
      out.write("   text-align: center;\n");
      out.write("   border: medium solid #ff00ff;\n");
      out.write("   \n");
      out.write("}\n");
      out.write(".taka h2{\n");
      out.write("   font-size: 17px;\n");
      out.write("   color:hotpink;\n");
      out.write("   text-align: center;\n");
      out.write("   border: medium solid white;\n");
      out.write("}\n");
      out.write(".form1{\n");
      out.write("\twidth:500px;\n");
      out.write("\tmargin:0 auto;\n");
      out.write("\tmargin-left:auto;\n");
      out.write("\tmargin-right:auto;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write(".search { \n");
      out.write("\tpadding:6px 15px 6px 30px;\n");
      out.write("\tmargin:3px; \n");
      out.write("\t \n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("<nav class=\"navbar navbar-inverse\">\n");
      out.write("\t\n");
      out.write("\t\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbarEexample7\">\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"#\">ASO書店</a>\n");
      out.write("\t\n");
      out.write("\t\t\t\t</div>\n");

LoginInfoDTO loginInfo = (LoginInfoDTO)session.getAttribute(SessionConst.SESSION_LOGININFO);

      out.write("\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarEexample7\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/top\">トップ画面</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">買い物かご</a></li>\n");
      out.write("\t\t\t\t\t\t");
 if(loginInfo == null ){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/MemberNew\">新規会員登録</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/login\">ログイン</a></li>\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a class=\"navbar-brand\" href=\"#\">ようこそ! ");
      out.print( loginInfo.getMemb_name() );
      out.write("さん</a><li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout\">ログアウト</a></li>\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t  <div class=\"row\" id=\"pwd-container\">\n");
      out.write("\n");
      out.write("\t\t    <div class=\"col-md-4\"></div>\n");
      out.write("\n");
      out.write("\t\t    <div class=\"col-md-4\">\n");
      out.write("\n");
      out.write("\t\t      <section class=\"login-form\">\n");
      out.write("\t\t      \t\n");
      out.write("\t\t        \n");
      out.write("\t\t       </section>\n");
      out.write("\t\t      </div>\n");
      out.write("\t\t    <div class=\"col-md-4\"></div>\n");
      out.write("\t\t   </div>\n");
      out.write("\t\t </div>\n");
      out.write("\t\t <nav class=\"taka\">\n");
      out.write("\t\t \t<h2>書籍検索</h2>\n");
      out.write("\t\t \t<h1>あ行からわ行で検索します。</h1>\n");
      out.write("\t\t \t<form class=\"form1\" action=\"");
      out.print(request.getContextPath() );
      out.write("/\" method=\"post\" >\n");
      out.write("   \t\t\t\t<span><input type=\"text\" name=\"booksearch\" class=\"search rounded\" placeholder=\"Search...\" size=\"15\" ></span>\n");
      out.write("    \t\t\t<span><input type=\"submit\" value=\"検索\" style=\"background-color:#ffffff;border-color:#ff6868;border-width:2px\"></span>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t \t\n");
      out.write("\t\t \t<h1>ジャンル</h1>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t  <li><a href=\"#\">一般教養</a></li>\n");
      out.write("\t\t\t  <li><a href=\"#\">語学</a></li>\n");
      out.write("\t\t\t  <li><a href=\"#\">情報系・PC関連</a></li>\n");
      out.write("\t\t\t  <li><a href=\"#\">介護・看護</a></li>\n");
      out.write("\t\t\t  <li><a href=\"#\">医療関連</a></li>\n");
      out.write("\t\t\t  <li><a href=\"#\">工業・電気関係</a></li>\n");
      out.write("\t\t\t  <li><a href=\"#\">法学関係</a></li>\n");
      out.write("\t\t\t  <li><a href=\"#\">国家試験対策本</a></li>\n");
      out.write("\t\t\t  <li><a href=\"#\">事務系</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</nav>\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("   \n");
      out.write("   \n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\n");
      out.write("<script src=\"view/img/js/jquery-2.1.4.js\"></script>\n");
      out.write("<script src=\"view/img/js/jquery-2.1.4.min.js\"></script>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
